#!/bin/bash
set -e

if [[ "$1" == "-h" || "$1" == "--help" ]]; then
    echo "Usage: $(basename "$0") [path] [pattern]"
    echo
    echo "Calculate bus factor and fraction of lines edited by the most active contributor for the files in a git repository."
    echo "It serches the code in the [path] and it can be additionally filtered using a regex [pattern]."
    exit 0
fi

# cleanup the temporary files
clean () { rm -f /tmp/busfk-files.tmp /tmp/busfk-results.tmp; }

clean

if [ "$#" -eq 0 ]; then
    DIR=$(pwd)
else
    DIR="$1"
fi

# we need to change the directory to use git
cd "$DIR"

if [ "$( git rev-parse --is-inside-work-tree 2>/dev/null )" != "true" ]; then
    echo "Error: $DIR is not a git repository"
    exit 1
fi

# list all files, ignore the .git directory
find "$DIR" -type f -not -path "*/.git/*" 2>/dev/null >/tmp/busfk-files.tmp

# filter the files using a [pattern]
if [ -n "$2" ]; then
    sed -i -n "/$2/p" /tmp/busfk-files.tmp
fi

while IFS= read -r file; do

    # skip files mentioned in .gitignore
    if [ -z "$( git check-ignore "$file" 2>&1 )" ]; then
        authors=$( git blame --line-porcelain "$file" 2>/dev/null \
                | sed -n 's/^author //p' \
                | sort \
                | uniq -c )

        # fraction of lines by the most active editor
        contrib=$( awk '{ if ($1 > max) max = $1; sum += $1 } END { if (sum > 0) printf "%.1f", max / sum * 100 }' <<< "$authors" )

        # number of unique editors
        busfactor=$( wc -l <<< "$authors" )

        lines=$( wc -l "$file" | awk '{ print $1 }' )

        # filter out empty files etc.
        if [ "$busfactor" -gt 0 ]; then
            printf "%4d %5.1f%% %6d %s\n" "$busfactor" "${contrib:-100.0}" "$lines" "$file" >> /tmp/busfk-results.tmp
        fi
    fi
done < /tmp/busfk-files.tmp

printf "  bf   max%%  lines path\n"
# sort by the bus factor
sort -k1,1 /tmp/busfk-results.tmp

printf "\nSummary (weighted averages):\n"
awk '{ l += $3; b += $1 * $3; f += $2 * $3 } END { printf "%4.1f %5.1f%% %6d", b/l, f/l, l }' /tmp/busfk-results.tmp
printf " %s\n" "$DIR"

clean
