#!/bin/bash

# pip install --upgrade ydiff

if [[ "$#" -eq 0 ||  "$1" == "-h" || "$1" == "--help" ]]; then
    echo "Usage: $(basename "$0") [diff flags] [dir|file] [dir|file]"
    echo
    echo "Show diff between files or directories in two columns."
    exit 0
fi

diff -u "$@" | ydiff -s

