#!/bin/bash
set -e

if [[ "$#" -eq 0 || "$1" == "-h" || "$1" == "--help" ]]; then
    echo "Usage: $(basename "$0") url json"
    echo
    echo "Make a simple POST request to URL with attached JSON data."
    exit 0
fi

URL="$1"
DATA="$2"
HEADERS='-H "accept: application/json" -H "Content-Type: application/json"'

# run json.tool to validate the JSON
echo "$DATA" | python -m json.tool 1> /dev/null

cmd="curl -X POST $URL $HEADERS -d '$DATA'"
echo "$cmd"
eval "$cmd"
